os: linux
language: python
cache:
    pip: true
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r ".[test]" . # install package + test dependencies
script: pytest -s # run tests
after_success:
  - codecov # submit coverage

